# Generated by Django 2.2.5 on 2019-12-15 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BoardApp', '0003_auto_20191215_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts_updated', related_query_name='post_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
