# Generated by Django 2.2.5 on 2019-12-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoardApp', '0004_post_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_subject',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
